import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/306",
  size: 15,
  colorRegions: [
    ["A", "A", "A", "B", "B", "B", "B", "B", "B", "B", "C", "C", "C", "C", "C"],
    ["A", "A", "A", "B", "B", "B", "B", "B", "B", "B", "C", "C", "C", "C", "C"],
    ["A", "A", "A", "A", "B", "A", "D", "D", "D", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "D", "C", "C", "C", "C", "C", "C"],
    ["E", "A", "A", "E", "A", "D", "D", "D", "D", "D", "D", "D", "C", "C", "C"],
    ["E", "E", "E", "E", "D", "D", "F", "D", "D", "D", "G", "D", "D", "C", "C"],
    ["E", "E", "E", "E", "D", "F", "F", "F", "D", "G", "G", "G", "D", "C", "C"],
    ["E", "E", "E", "H", "D", "F", "F", "F", "D", "G", "G", "G", "D", "C", "C"],
    ["I", "E", "E", "H", "D", "D", "D", "D", "D", "D", "D", "D", "D", "C", "J"],
    ["I", "I", "I", "H", "D", "K", "K", "D", "D", "D", "K", "K", "D", "J", "J"],
    ["L", "I", "M", "M", "D", "D", "K", "K", "K", "K", "K", "D", "D", "J", "J"],
    ["L", "I", "I", "M", "M", "D", "D", "D", "D", "D", "D", "D", "J", "J", "J"],
    ["L", "I", "I", "I", "I", "I", "N", "N", "N", "N", "N", "N", "N", "J", "J"],
    ["L", "I", "I", "I", "I", "O", "N", "N", "N", "N", "N", "N", "N", "N", "J"],
    ["L", "L", "L", "L", "O", "O", "N", "N", "N", "N", "N", "N", "N", "N", "J"],
  ],
  regionColors: {
    A: lightWisteria,
    B: nomad,
    C: anakiwa,
    D: macNCheese,
    E: turquoiseBlue,
    F: altoMain,
    G: white,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: bittersweet,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: -1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
