import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/297",
  size: 15,
  colorRegions: [
    ["A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "A", "C", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "C", "C", "C", "C", "C", "C", "B", "B", "B", "B", "B", "B", "D"],
    ["A", "A", "E", "C", "C", "C", "C", "B", "B", "B", "B", "B", "B", "D", "D"],
    ["A", "A", "E", "C", "E", "C", "C", "C", "C", "B", "F", "B", "B", "B", "D"],
    ["A", "A", "E", "E", "E", "E", "C", "A", "C", "C", "F", "F", "B", "B", "B"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "C", "C", "G", "G", "G", "G", "B"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "C", "G", "H", "H", "H", "H"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "C", "C", "H", "I", "I", "H"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "J", "C", "C", "I", "I", "H"],
    ["A", "A", "A", "K", "K", "K", "A", "A", "A", "J", "J", "J", "I", "I", "H"],
    ["A", "A", "A", "A", "A", "K", "K", "L", "L", "L", "J", "J", "I", "I", "I"],
    ["A", "A", "A", "A", "A", "M", "M", "M", "N", "N", "J", "N", "I", "I", "I"],
    ["A", "A", "A", "A", "M", "M", "O", "M", "N", "N", "N", "N", "I", "I", "I"],
    ["A", "A", "A", "A", "A", "O", "O", "M", "M", "N", "N", "N", "N", "N", "I"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: -1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
