import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/302",
  size: 17,
  colorRegions: [
    ["A", "B", "B", "B", "B", "B", "B", "B", "B", "C", "C", "B", "B", "D", "D", "D", "D"],
    ["A", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "D", "D", "D", "D"],
    ["A", "A", "A", "B", "B", "B", "B", "B", "B", "B", "B", "E", "D", "D", "D", "D", "D"],
    ["A", "A", "A", "B", "B", "B", "B", "B", "B", "B", "E", "E", "D", "D", "D", "D", "D"],
    ["A", "A", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "F", "F", "D", "G", "G"],
    ["A", "A", "A", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "F", "G", "G", "H"],
    ["A", "A", "I", "I", "I", "B", "B", "B", "B", "B", "B", "B", "B", "B", "H", "H", "H"],
    ["A", "A", "I", "I", "I", "B", "I", "B", "B", "B", "B", "B", "B", "B", "B", "B", "H"],
    ["A", "A", "I", "J", "I", "I", "I", "B", "B", "B", "B", "K", "B", "B", "B", "B", "H"],
    ["A", "A", "A", "J", "K", "K", "K", "K", "K", "K", "K", "K", "K", "B", "B", "B", "H"],
    ["A", "A", "A", "A", "K", "K", "L", "K", "K", "K", "K", "K", "K", "K", "B", "H", "H"],
    ["A", "A", "A", "A", "K", "M", "L", "K", "K", "K", "K", "K", "K", "K", "B", "B", "H"],
    ["A", "A", "A", "A", "A", "M", "M", "K", "K", "K", "N", "K", "K", "K", "K", "K", "K"],
    ["A", "A", "A", "A", "A", "A", "M", "K", "K", "N", "N", "K", "K", "K", "K", "K", "O"],
    ["P", "P", "A", "A", "A", "A", "M", "M", "M", "M", "M", "M", "M", "K", "K", "O", "O"],
    ["P", "P", "A", "A", "A", "A", "M", "M", "Q", "Q", "Q", "Q", "Q", "K", "K", "O", "O"],
    ["P", "P", "P", "P", "P", "A", "M", "M", "Q", "Q", "Q", "Q", "Q", "K", "O", "O", "O"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: white,
    Q: macNCheese,
  },
  solutionsCount: -1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
