import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/230",
  size: 15,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "C", "C", "C", "C"],
    ["A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "D", "C", "C"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "D", "D", "C"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "D", "E", "E"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "D", "F", "F"],
    ["A", "A", "A", "G", "A", "A", "A", "A", "A", "A", "A", "A", "D", "F", "F"],
    ["A", "G", "G", "G", "A", "A", "A", "A", "A", "A", "A", "A", "D", "F", "F"],
    ["A", "G", "G", "G", "G", "A", "H", "A", "I", "I", "A", "A", "D", "D", "F"],
    ["A", "G", "G", "G", "G", "A", "H", "H", "H", "H", "H", "H", "H", "D", "F"],
    ["A", "G", "G", "J", "J", "J", "J", "H", "H", "H", "H", "H", "H", "H", "F"],
    ["K", "K", "K", "L", "J", "J", "J", "J", "J", "J", "H", "H", "H", "H", "H"],
    ["K", "K", "L", "L", "L", "J", "J", "J", "J", "J", "J", "H", "H", "H", "H"],
    ["K", "K", "L", "L", "L", "L", "M", "M", "J", "J", "J", "J", "H", "H", "H"],
    ["K", "K", "L", "L", "L", "N", "N", "N", "J", "O", "J", "J", "H", "H", "H"],
    ["K", "K", "L", "L", "L", "L", "L", "N", "N", "O", "J", "J", "H", "H", "H"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
