import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  canCan,
  celadon,
  chardonnay,
  feijoa,
  halfBaked,
  lightOrchid,
  lightWisteria,
  malibu,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/205",
  size: 15,
  colorRegions: [
    ["A", "A", "A", "A", "B", "B", "C", "C", "C", "C", "C", "C", "D", "D", "D"],
    ["A", "A", "A", "B", "B", "B", "C", "C", "C", "C", "C", "D", "D", "D", "D"],
    ["A", "A", "A", "B", "B", "B", "B", "C", "C", "E", "C", "D", "D", "D", "D"],
    ["A", "A", "F", "B", "B", "B", "B", "C", "C", "E", "E", "E", "D", "D", "D"],
    ["A", "A", "F", "B", "B", "B", "B", "B", "C", "E", "E", "D", "D", "D", "D"],
    ["A", "F", "F", "B", "B", "F", "F", "B", "B", "B", "E", "E", "D", "D", "D"],
    ["A", "F", "F", "F", "F", "F", "F", "B", "B", "E", "E", "E", "D", "G", "D"],
    ["F", "F", "F", "F", "H", "H", "H", "B", "B", "E", "E", "G", "D", "G", "G"],
    ["F", "H", "H", "H", "H", "H", "H", "I", "E", "E", "E", "G", "G", "G", "G"],
    ["F", "J", "H", "H", "H", "H", "I", "I", "I", "I", "I", "G", "G", "K", "K"],
    ["J", "J", "J", "H", "I", "I", "I", "I", "I", "I", "G", "G", "K", "K", "K"],
    ["J", "J", "J", "L", "L", "L", "L", "I", "I", "I", "G", "K", "K", "K", "K"],
    ["M", "M", "J", "L", "L", "L", "I", "I", "I", "I", "G", "K", "K", "K", "K"],
    ["M", "M", "N", "N", "L", "O", "O", "O", "O", "I", "G", "K", "K", "K", "K"],
    ["M", "M", "M", "N", "N", "O", "O", "O", "O", "I", "I", "I", "K", "K", "K"],
  ],
  regionColors: {
    A: anakiwa,
    B: altoMain,
    C: lightWisteria,
    D: chardonnay,
    E: bittersweet,
    F: celadon,
    G: lightOrchid,
    H: saharaSand,
    I: nomad,
    J: halfBaked,
    K: turquoiseBlue,
    L: canCan,
    M: malibu,
    N: feijoa,
    O: atomicTangerine,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
