import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/214",
  size: 15,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "B"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "B"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "C", "C", "B", "B", "B", "B", "D"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "C", "C", "E", "E", "E", "D", "D"],
    ["A", "A", "A", "A", "A", "A", "F", "A", "C", "C", "E", "E", "E", "D", "D"],
    ["A", "A", "A", "A", "G", "G", "F", "A", "A", "A", "E", "E", "E", "E", "D"],
    ["A", "A", "A", "H", "G", "I", "F", "F", "I", "A", "A", "E", "E", "E", "D"],
    ["A", "A", "A", "H", "I", "I", "I", "I", "I", "I", "A", "E", "E", "D", "D"],
    ["A", "A", "J", "H", "H", "H", "I", "I", "I", "I", "A", "A", "E", "E", "E"],
    ["A", "J", "J", "H", "H", "H", "I", "I", "I", "I", "A", "E", "E", "E", "E"],
    ["K", "J", "J", "J", "H", "H", "H", "H", "L", "I", "A", "A", "A", "E", "E"],
    ["K", "K", "J", "J", "H", "H", "H", "J", "L", "L", "L", "L", "A", "A", "E"],
    ["K", "K", "K", "J", "J", "J", "J", "J", "M", "L", "L", "L", "N", "N", "N"],
    ["K", "K", "K", "K", "K", "K", "J", "J", "M", "L", "L", "L", "O", "N", "N"],
    ["K", "K", "K", "K", "K", "K", "J", "M", "M", "M", "M", "L", "O", "O", "N"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
