import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/252",
  size: 14,
  colorRegions: [
    ["A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "B", "C", "C", "C"],
    ["D", "D", "A", "E", "A", "A", "B", "B", "B", "B", "C", "C", "C", "F"],
    ["D", "A", "A", "E", "A", "B", "B", "B", "B", "B", "G", "H", "C", "F"],
    ["D", "D", "A", "A", "A", "A", "B", "B", "B", "B", "G", "H", "F", "F"],
    ["D", "D", "D", "I", "I", "A", "A", "A", "B", "B", "G", "G", "G", "G"],
    ["D", "D", "J", "I", "K", "A", "A", "A", "A", "B", "B", "G", "G", "G"],
    ["D", "L", "J", "I", "K", "K", "K", "K", "K", "K", "B", "B", "B", "B"],
    ["D", "L", "J", "I", "I", "K", "K", "K", "K", "B", "B", "B", "B", "M"],
    ["D", "J", "J", "J", "I", "K", "K", "K", "K", "N", "B", "B", "M", "M"],
    ["D", "J", "J", "J", "J", "K", "K", "K", "N", "N", "N", "B", "B", "M"],
    ["D", "J", "J", "J", "J", "K", "J", "K", "K", "M", "M", "M", "M", "M"],
    ["D", "D", "J", "J", "J", "J", "J", "K", "M", "M", "M", "M", "M", "M"],
    ["D", "D", "D", "J", "J", "J", "J", "K", "M", "M", "M", "M", "M", "M"],
    ["D", "J", "J", "J", "J", "J", "J", "M", "M", "M", "M", "M", "M", "M"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
