import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/310",
  size: 16,
  colorRegions: [
    ["A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "B", "B", "B", "B", "C", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "A", "A", "B", "D", "C", "C", "B", "B", "B", "B", "C", "B", "B", "B"],
    ["A", "A", "A", "A", "A", "D", "D", "C", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "A", "A", "E", "E", "E", "E", "E", "E", "E", "C", "F", "C", "C", "C"],
    ["A", "A", "A", "A", "A", "A", "E", "E", "E", "E", "E", "E", "F", "C", "C", "C"],
    ["G", "A", "A", "A", "A", "A", "A", "A", "E", "E", "E", "E", "E", "E", "E", "E"],
    ["G", "A", "A", "A", "A", "A", "A", "A", "E", "A", "A", "E", "H", "H", "I", "I"],
    ["G", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "I", "I"],
    ["G", "A", "A", "A", "A", "A", "A", "A", "J", "J", "J", "A", "A", "A", "I", "I"],
    ["G", "G", "A", "A", "A", "A", "A", "K", "J", "J", "J", "L", "L", "L", "L", "L"],
    ["G", "G", "A", "A", "A", "A", "K", "K", "M", "J", "J", "L", "L", "L", "L", "L"],
    ["G", "G", "G", "G", "G", "A", "A", "M", "M", "J", "J", "L", "L", "L", "L", "L"],
    ["G", "G", "G", "G", "G", "A", "M", "M", "M", "N", "N", "L", "L", "L", "L", "O"],
    ["G", "G", "G", "G", "G", "A", "G", "M", "M", "M", "M", "L", "L", "L", "O", "O"],
    ["G", "P", "P", "P", "G", "G", "G", "G", "G", "M", "M", "L", "L", "L", "O", "O"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: white,
  },
  solutionsCount: -1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
