import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/231",
  size: 13,
  colorRegions: [
    ["A", "B", "C", "D", "D", "E", "E", "E", "F", "F", "F", "F", "F"],
    ["A", "B", "C", "D", "D", "D", "D", "E", "F", "F", "F", "F", "F"],
    ["A", "B", "B", "B", "B", "B", "D", "D", "F", "F", "F", "F", "F"],
    ["B", "B", "G", "G", "B", "B", "B", "D", "F", "F", "F", "F", "H"],
    ["B", "B", "G", "G", "B", "I", "B", "D", "F", "F", "H", "H", "H"],
    ["B", "I", "I", "I", "I", "I", "D", "D", "F", "F", "H", "H", "H"],
    ["I", "I", "I", "J", "J", "J", "D", "F", "F", "F", "H", "H", "H"],
    ["I", "I", "J", "J", "J", "J", "J", "J", "J", "F", "F", "F", "H"],
    ["I", "I", "J", "J", "K", "K", "K", "K", "J", "F", "F", "F", "F"],
    ["I", "I", "J", "J", "K", "K", "K", "K", "K", "L", "F", "F", "F"],
    ["I", "J", "J", "J", "J", "K", "M", "M", "K", "L", "L", "L", "L"],
    ["I", "I", "J", "J", "J", "K", "M", "M", "K", "K", "K", "K", "K"],
    ["J", "J", "J", "J", "J", "K", "K", "K", "K", "K", "K", "K", "K"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
