import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/768",
  size: 16,
  colorRegions: [
    ["M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "K", "K", "A", "A", "A", "A"],
    ["M", "O", "M", "M", "M", "J", "M", "M", "M", "M", "E", "A", "A", "A", "A", "A"],
    ["C", "O", "O", "M", "J", "J", "J", "J", "J", "E", "E", "A", "A", "A", "A", "A"],
    ["C", "C", "O", "J", "J", "J", "J", "J", "J", "B", "B", "B", "A", "A", "A", "A"],
    ["C", "C", "J", "J", "J", "J", "J", "G", "G", "B", "B", "B", "A", "A", "A", "A"],
    ["C", "C", "C", "C", "C", "C", "J", "G", "B", "B", "B", "B", "B", "B", "A", "A"],
    ["C", "C", "C", "C", "C", "C", "B", "G", "B", "B", "B", "B", "B", "B", "A", "A"],
    ["C", "C", "C", "C", "C", "B", "B", "B", "B", "B", "B", "B", "B", "A", "A", "A"],
    ["C", "C", "C", "C", "C", "C", "B", "B", "B", "B", "B", "B", "B", "A", "A", "A"],
    ["C", "C", "C", "C", "C", "C", "C", "H", "B", "B", "B", "B", "B", "B", "A", "A"],
    ["I", "C", "F", "F", "F", "F", "F", "H", "B", "B", "B", "N", "N", "A", "A", "A"],
    ["I", "C", "C", "C", "F", "I", "I", "H", "H", "B", "D", "D", "D", "D", "A", "A"],
    ["I", "I", "I", "I", "I", "I", "I", "I", "I", "D", "D", "D", "D", "D", "A", "A"],
    ["I", "I", "I", "I", "I", "I", "I", "I", "I", "I", "D", "D", "D", "D", "D", "A"],
    ["I", "I", "P", "I", "I", "I", "I", "I", "I", "I", "L", "D", "D", "D", "D", "D"],
    ["I", "P", "P", "I", "I", "I", "I", "I", "I", "L", "L", "L", "L", "D", "D", "D"],
  ],
  regionColors: {
     A: lightWisteria,
      B: chardonnay,
      C: anakiwa,
      D: celadon,
      E: altoMain,
      F: bittersweet,
      G: saharaSand,
      H: nomad,
      I: lightOrchid,
      J: halfBaked,
      K: turquoiseBlue,
      L: atomicTangerine,
      M: lightGreen,
      N: emerald,
      O: macNCheese,
      P: coldPurple,
  },
  solutionsCount: 1,
  createdBy: "VictorBandoiu",
  creatorLink: "https://www.instagram.com/victorban72/",
};

export default level;
