import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/242",
  size: 15,
  colorRegions: [
    ["A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "A", "A", "C", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "C", "C", "C", "C", "D", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "C", "C", "E", "E", "D", "D", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "A", "C", "C", "D", "D", "D", "D", "D", "D", "D", "B", "B", "B"],
    ["A", "A", "C", "C", "C", "D", "D", "F", "F", "F", "F", "D", "B", "B", "B"],
    ["G", "G", "C", "C", "C", "C", "D", "F", "F", "H", "I", "D", "B", "B", "B"],
    ["G", "G", "G", "G", "G", "C", "D", "F", "F", "H", "I", "I", "I", "I", "I"],
    ["G", "G", "G", "G", "G", "C", "C", "F", "F", "F", "F", "I", "I", "I", "J"],
    ["G", "G", "G", "G", "G", "G", "C", "F", "F", "F", "F", "F", "K", "K", "J"],
    ["G", "G", "G", "G", "G", "G", "G", "G", "F", "F", "F", "L", "K", "K", "J"],
    ["G", "G", "G", "G", "G", "G", "G", "G", "F", "F", "F", "L", "L", "K", "K"],
    ["M", "G", "G", "G", "G", "G", "N", "G", "G", "F", "L", "L", "L", "L", "L"],
    ["M", "G", "G", "G", "G", "G", "N", "N", "G", "G", "L", "L", "L", "L", "L"],
    ["M", "G", "G", "G", "G", "G", "N", "N", "N", "G", "O", "O", "O", "O", "O"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
