import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/221",
  size: 13,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "B", "B", "C", "C", "C", "C", "C"],
    ["A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "C", "C"],
    ["A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "C", "C"],
    ["A", "D", "A", "A", "E", "A", "A", "F", "B", "B", "B", "C", "C"],
    ["D", "D", "A", "E", "E", "E", "A", "F", "F", "B", "B", "C", "C"],
    ["D", "D", "D", "E", "G", "E", "E", "E", "E", "E", "B", "C", "C"],
    ["D", "D", "D", "D", "D", "E", "E", "E", "E", "E", "E", "H", "C"],
    ["D", "D", "D", "D", "D", "D", "E", "E", "E", "I", "E", "H", "C"],
    ["D", "D", "D", "D", "E", "E", "E", "E", "I", "I", "J", "J", "C"],
    ["D", "D", "K", "K", "E", "E", "E", "I", "I", "I", "J", "J", "J"],
    ["D", "K", "K", "K", "K", "K", "E", "I", "I", "I", "I", "I", "I"],
    ["K", "K", "L", "L", "K", "K", "K", "K", "K", "M", "I", "I", "I"],
    ["K", "L", "L", "L", "L", "K", "K", "K", "K", "M", "M", "I", "I"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
