import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/239",
  size: 15,
  colorRegions: [
    ["A", "A", "B", "B", "B", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "A", "B", "B", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "A", "B", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "A", "A", "A", "A", "C", "D", "C", "D", "C", "C", "C", "C", "C"],
    ["E", "A", "A", "A", "A", "A", "F", "D", "D", "D", "C", "C", "C", "C", "C"],
    ["E", "E", "E", "E", "A", "A", "F", "F", "F", "F", "C", "G", "C", "C", "C"],
    ["E", "E", "E", "E", "E", "A", "A", "F", "F", "H", "C", "G", "C", "C", "C"],
    ["E", "E", "E", "E", "E", "A", "A", "A", "A", "H", "H", "H", "C", "C", "C"],
    ["E", "I", "I", "I", "E", "A", "A", "A", "A", "H", "J", "H", "C", "C", "C"],
    ["E", "E", "I", "I", "I", "I", "A", "A", "K", "K", "J", "J", "C", "C", "C"],
    ["E", "I", "I", "I", "I", "I", "A", "K", "K", "K", "K", "K", "L", "L", "L"],
    ["E", "I", "I", "I", "I", "I", "A", "A", "A", "A", "K", "L", "L", "M", "M"],
    ["E", "I", "I", "I", "I", "A", "A", "A", "A", "A", "K", "L", "L", "M", "N"],
    ["I", "I", "O", "I", "I", "I", "I", "A", "A", "A", "K", "L", "L", "N", "N"],
    ["I", "O", "O", "O", "O", "I", "A", "A", "A", "A", "K", "L", "L", "N", "N"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: -1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
