import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/336",
  size: 15,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "B", "B", "B"],
    ["A", "A", "A", "C", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A"],
    ["D", "A", "C", "C", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A"],
    ["D", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A"],
    ["D", "D", "E", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A"],
    ["D", "E", "E", "A", "A", "F", "A", "G", "G", "G", "A", "A", "A", "A", "A"],
    ["E", "E", "E", "E", "F", "F", "A", "G", "G", "G", "G", "G", "G", "A", "A"],
    ["E", "E", "E", "H", "H", "H", "A", "G", "G", "G", "I", "G", "G", "G", "G"],
    ["E", "E", "E", "H", "H", "H", "A", "G", "G", "I", "I", "G", "G", "G", "G"],
    ["E", "E", "E", "E", "H", "H", "H", "J", "J", "J", "I", "I", "I", "K", "K"],
    ["E", "E", "E", "E", "E", "H", "H", "J", "J", "J", "J", "L", "K", "K", "K"],
    ["E", "E", "E", "E", "E", "H", "H", "H", "H", "J", "N", "L", "L", "L", "K"],
    ["E", "E", "E", "E", "E", "H", "M", "M", "H", "J", "N", "N", "L", "L", "K"],
    ["E", "E", "E", "E", "E", "M", "M", "M", "H", "J", "J", "J", "J", "L", "L"],
    ["E", "E", "E", "E", "E", "E", "M", "M", "M", "M", "M", "M", "J", "O", "O"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
