import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lavenderRose,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/215",
  size: 15,
  colorRegions: [
    ["A", "B", "B", "B", "C", "D", "D", "D", "D", "D", "D", "D", "D", "D", "D"],
    ["A", "B", "B", "C", "C", "C", "D", "D", "D", "D", "D", "D", "D", "D", "D"],
    ["A", "B", "B", "B", "B", "B", "D", "D", "D", "D", "D", "D", "D", "D", "D"],
    ["A", "A", "A", "A", "B", "B", "D", "D", "E", "D", "D", "D", "D", "D", "D"],
    ["A", "A", "A", "A", "B", "B", "B", "E", "E", "D", "D", "D", "D", "D", "D"],
    ["A", "A", "A", "A", "A", "B", "B", "E", "E", "D", "D", "D", "F", "F", "D"],
    ["A", "A", "A", "A", "A", "B", "G", "G", "G", "D", "D", "D", "H", "H", "H"],
    ["A", "A", "A", "A", "A", "A", "G", "G", "G", "G", "G", "D", "H", "H", "I"],
    ["A", "A", "A", "A", "A", "A", "G", "G", "G", "G", "G", "G", "H", "I", "I"],
    ["A", "A", "A", "A", "A", "A", "G", "J", "J", "J", "K", "K", "H", "I", "I"],
    ["A", "A", "L", "L", "A", "A", "A", "A", "J", "J", "K", "K", "K", "K", "K"],
    ["A", "A", "L", "L", "L", "L", "A", "A", "J", "J", "K", "K", "K", "K", "K"],
    ["M", "A", "L", "L", "L", "L", "N", "N", "N", "J", "K", "K", "K", "K", "K"],
    ["M", "A", "L", "L", "L", "L", "L", "N", "N", "N", "N", "O", "O", "O", "K"],
    ["M", "A", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "O", "K"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: lavenderRose,
    Q: white,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
