import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/218",
  size: 13,
  colorRegions: [
    ["A", "B", "B", "B", "B", "B", "C", "C", "C", "C", "C", "C", "C"],
    ["A", "B", "B", "B", "B", "B", "B", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "B", "B", "B", "B", "B", "B", "C", "C", "C", "C", "C"],
    ["A", "A", "B", "B", "B", "B", "B", "B", "B", "C", "C", "D", "C"],
    ["A", "A", "B", "E", "B", "B", "B", "B", "D", "D", "D", "D", "C"],
    ["A", "A", "B", "E", "E", "E", "B", "D", "D", "D", "F", "F", "F"],
    ["A", "A", "G", "E", "E", "E", "E", "D", "D", "D", "F", "F", "F"],
    ["A", "A", "G", "E", "E", "H", "E", "E", "E", "E", "E", "I", "I"],
    ["A", "A", "G", "E", "H", "H", "E", "E", "E", "E", "I", "I", "I"],
    ["A", "A", "A", "E", "H", "H", "H", "H", "E", "J", "I", "I", "I"],
    ["A", "A", "A", "E", "H", "K", "L", "L", "E", "J", "J", "I", "I"],
    ["A", "A", "A", "E", "H", "K", "L", "L", "M", "M", "M", "M", "M"],
    ["A", "E", "E", "E", "H", "K", "K", "K", "M", "M", "M", "M", "M"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
