import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/278",
  size: 13,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "B", "B", "B", "C", "C", "C", "D"],
    ["A", "A", "A", "A", "A", "A", "A", "B", "B", "E", "E", "E", "D"],
    ["A", "A", "A", "A", "A", "A", "F", "F", "B", "B", "E", "D", "D"],
    ["A", "A", "A", "A", "A", "A", "F", "F", "F", "B", "B", "B", "B"],
    ["A", "A", "A", "A", "A", "A", "A", "F", "G", "B", "G", "B", "B"],
    ["A", "A", "A", "A", "A", "A", "A", "F", "G", "G", "G", "G", "G"],
    ["A", "A", "H", "H", "I", "I", "I", "F", "F", "F", "G", "G", "G"],
    ["J", "H", "H", "H", "I", "I", "I", "F", "F", "G", "G", "F", "G"],
    ["J", "H", "J", "H", "H", "I", "I", "I", "F", "F", "F", "F", "F"],
    ["J", "J", "J", "H", "H", "H", "H", "I", "K", "K", "F", "F", "F"],
    ["J", "J", "L", "L", "H", "H", "H", "I", "K", "K", "K", "K", "K"],
    ["M", "J", "L", "L", "L", "H", "L", "L", "K", "K", "K", "K", "K"],
    ["M", "M", "M", "M", "L", "L", "L", "K", "K", "K", "K", "K", "K"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
