import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/271",
  size: 15,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A"],
    ["A", "A", "A", "A", "B", "A", "A", "A", "A", "C", "A", "A", "A", "A", "A"],
    ["A", "A", "A", "B", "B", "B", "A", "C", "C", "C", "C", "A", "A", "A", "A"],
    ["A", "A", "B", "B", "B", "B", "B", "C", "D", "D", "C", "A", "A", "A", "A"],
    ["A", "A", "A", "B", "B", "B", "E", "C", "C", "D", "D", "D", "F", "A", "A"],
    ["A", "A", "A", "A", "B", "E", "E", "E", "E", "D", "D", "D", "F", "A", "A"],
    ["A", "A", "A", "A", "E", "E", "E", "G", "D", "D", "D", "D", "F", "A", "A"],
    ["A", "A", "E", "E", "E", "E", "G", "G", "G", "D", "D", "D", "F", "H", "H"],
    ["A", "A", "E", "E", "I", "J", "G", "G", "G", "G", "D", "D", "F", "H", "H"],
    ["A", "A", "K", "I", "I", "J", "G", "G", "G", "L", "D", "D", "F", "H", "H"],
    ["A", "K", "K", "K", "I", "I", "I", "G", "L", "L", "L", "F", "F", "F", "H"],
    ["K", "K", "K", "K", "K", "I", "I", "I", "I", "I", "L", "F", "F", "F", "H"],
    ["M", "K", "K", "K", "I", "I", "I", "I", "I", "I", "F", "F", "F", "F", "F"],
    ["M", "M", "K", "N", "N", "I", "I", "I", "I", "I", "I", "F", "F", "F", "O"],
    ["M", "M", "N", "N", "N", "I", "I", "I", "I", "I", "I", "I", "F", "O", "O"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
