import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  coldPurple,
  halfBaked,
  lightWisteria,
  macNCheese,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/305",
  size: 13,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "B"],
    ["A", "A", "A", "A", "A", "C", "C", "C", "B", "B", "B", "B", "B"],
    ["A", "A", "A", "A", "A", "A", "A", "C", "B", "B", "B", "B", "B"],
    ["A", "A", "D", "A", "C", "C", "C", "C", "C", "C", "C", "B", "B"],
    ["A", "D", "D", "C", "C", "E", "C", "C", "C", "F", "C", "C", "B"],
    ["A", "G", "D", "C", "E", "E", "E", "C", "F", "F", "F", "C", "B"],
    ["A", "G", "G", "C", "E", "E", "E", "C", "F", "F", "F", "C", "B"],
    ["H", "H", "H", "C", "C", "C", "C", "C", "C", "C", "C", "C", "B"],
    ["H", "H", "H", "C", "I", "I", "C", "C", "C", "I", "I", "C", "B"],
    ["H", "H", "H", "C", "C", "I", "I", "I", "I", "I", "C", "C", "J"],
    ["H", "H", "H", "K", "C", "C", "C", "C", "C", "C", "C", "J", "J"],
    ["H", "H", "H", "K", "K", "K", "K", "K", "K", "L", "L", "L", "J"],
    ["H", "H", "H", "H", "K", "K", "K", "K", "K", "L", "M", "M", "M"],
  ],
  regionColors: {
    A: lightWisteria,
    B: anakiwa,
    C: macNCheese,
    D: celadon,
    E: altoMain,
    F: altoMain,
    G: saharaSand,
    H: nomad,
    I: bittersweet,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: coldPurple,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
