import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/226",
  size: 13,
  colorRegions: [
    ["A", "A", "A", "A", "B", "B", "B", "B", "B", "B", "B", "B", "B"],
    ["A", "A", "A", "A", "B", "B", "B", "B", "B", "B", "C", "C", "C"],
    ["A", "A", "A", "A", "B", "B", "B", "B", "B", "B", "C", "D", "D"],
    ["A", "A", "A", "A", "B", "E", "E", "F", "B", "B", "C", "C", "C"],
    ["A", "A", "G", "G", "G", "E", "E", "F", "F", "F", "C", "C", "C"],
    ["A", "A", "G", "G", "E", "E", "H", "H", "H", "H", "C", "C", "C"],
    ["A", "A", "G", "G", "G", "G", "I", "J", "H", "H", "H", "C", "C"],
    ["A", "G", "G", "K", "G", "I", "I", "J", "J", "H", "H", "C", "C"],
    ["A", "A", "G", "K", "G", "G", "I", "I", "I", "I", "I", "I", "C"],
    ["A", "A", "G", "G", "G", "G", "I", "I", "I", "I", "I", "I", "I"],
    ["A", "L", "L", "L", "L", "G", "G", "I", "I", "I", "I", "I", "I"],
    ["A", "A", "L", "L", "L", "L", "L", "I", "M", "I", "I", "I", "I"],
    ["A", "A", "L", "L", "L", "L", "L", "L", "M", "M", "I", "I", "I"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
