import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/279",
  size: 13,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "E"],
    ["A", "B", "A", "B", "A", "A", "A", "A", "A", "C", "A", "A", "E"],
    ["A", "B", "B", "B", "A", "A", "D", "A", "C", "C", "A", "A", "E"],
    ["A", "A", "B", "A", "A", "D", "D", "D", "E", "C", "A", "A", "E"],
    ["A", "B", "B", "B", "A", "A", "D", "E", "E", "C", "A", "A", "E"],
    ["A", "B", "F", "B", "A", "A", "G", "E", "C", "C", "C", "E", "E"],
    ["A", "A", "F", "F", "A", "G", "G", "E", "E", "E", "E", "E", "E"],
    ["A", "A", "H", "F", "A", "A", "G", "E", "I", "E", "I", "E", "E"],
    ["A", "H", "H", "A", "A", "J", "E", "E", "I", "I", "I", "E", "K"],
    ["A", "A", "H", "A", "J", "J", "J", "E", "E", "I", "E", "E", "K"],
    ["A", "A", "H", "A", "A", "J", "E", "E", "I", "I", "I", "K", "K"],
    ["A", "H", "H", "H", "E", "E", "E", "E", "I", "L", "I", "M", "K"],
    ["E", "E", "E", "E", "E", "E", "E", "E", "L", "L", "M", "M", "K"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
