import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/263",
  size: 15,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "B"],
    ["A", "A", "A", "A", "C", "A", "D", "A", "A", "A", "A", "B", "B", "B", "B"],
    ["A", "A", "A", "C", "C", "D", "D", "D", "E", "E", "B", "B", "F", "B", "B"],
    ["C", "A", "A", "C", "C", "C", "D", "E", "E", "E", "E", "F", "F", "B", "B"],
    ["C", "C", "C", "C", "C", "C", "C", "E", "E", "E", "E", "E", "F", "G", "B"],
    ["C", "C", "C", "C", "H", "G", "G", "G", "G", "G", "I", "E", "G", "G", "B"],
    ["C", "C", "C", "H", "H", "H", "G", "G", "G", "I", "I", "I", "G", "G", "G"],
    ["C", "J", "C", "C", "H", "G", "G", "G", "G", "G", "I", "G", "G", "G", "G"],
    ["J", "J", "C", "J", "J", "G", "G", "J", "G", "G", "G", "G", "G", "G", "K"],
    ["J", "J", "C", "J", "J", "J", "J", "J", "J", "L", "G", "G", "G", "K", "K"],
    ["J", "J", "J", "J", "J", "M", "M", "M", "L", "L", "L", "G", "G", "G", "K"],
    ["J", "J", "J", "J", "J", "M", "N", "N", "N", "L", "N", "G", "G", "G", "K"],
    ["J", "J", "J", "J", "M", "M", "O", "O", "N", "N", "N", "N", "N", "K", "K"],
    ["J", "J", "J", "J", "J", "J", "O", "O", "O", "N", "N", "N", "N", "N", "K"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
