import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/212",
  size: 14,
  colorRegions: [
    ["A", "B", "B", "B", "B", "C", "C", "C", "C", "C", "C", "C", "D", "D"],
    ["A", "A", "B", "E", "E", "E", "C", "C", "C", "C", "C", "D", "D", "D"],
    ["A", "A", "B", "E", "E", "E", "E", "C", "F", "C", "C", "D", "D", "D"],
    ["A", "A", "A", "A", "G", "E", "E", "E", "F", "C", "C", "C", "D", "D"],
    ["A", "A", "A", "G", "G", "E", "E", "E", "E", "E", "C", "C", "D", "D"],
    ["A", "A", "A", "G", "G", "G", "G", "E", "G", "E", "E", "C", "D", "D"],
    ["A", "A", "A", "G", "G", "G", "G", "G", "G", "E", "E", "E", "D", "D"],
    ["A", "A", "A", "G", "G", "G", "G", "G", "G", "G", "H", "H", "D", "D"],
    ["A", "A", "A", "I", "G", "I", "I", "I", "G", "J", "J", "J", "J", "D"],
    ["A", "A", "A", "I", "I", "I", "I", "I", "G", "J", "J", "J", "K", "K"],
    ["A", "A", "A", "I", "L", "L", "I", "I", "I", "M", "J", "J", "K", "K"],
    ["A", "A", "L", "L", "L", "L", "I", "I", "I", "M", "J", "J", "J", "K"],
    ["A", "A", "L", "L", "L", "L", "L", "N", "N", "N", "J", "J", "J", "J"],
    ["A", "A", "A", "L", "L", "L", "L", "L", "N", "N", "N", "N", "N", "J"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
