import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/219",
  size: 13,
  colorRegions: [
    ["A", "A", "B", "B", "B", "B", "B", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "B", "B", "B", "B", "C", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "B", "A", "B", "B", "C", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "A", "A", "B", "D", "C", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "A", "A", "B", "D", "E", "E", "E", "E", "E", "C", "C"],
    ["A", "A", "A", "A", "B", "B", "E", "F", "E", "E", "E", "C", "C"],
    ["G", "A", "A", "A", "A", "B", "F", "F", "F", "E", "E", "E", "C"],
    ["G", "A", "A", "A", "A", "B", "F", "H", "H", "E", "E", "E", "E"],
    ["G", "A", "I", "I", "J", "J", "J", "J", "J", "E", "E", "E", "E"],
    ["K", "I", "I", "I", "J", "J", "J", "J", "J", "J", "J", "J", "E"],
    ["K", "I", "I", "I", "I", "J", "L", "L", "J", "J", "J", "J", "J"],
    ["K", "I", "I", "I", "I", "L", "L", "L", "M", "M", "J", "J", "J"],
    ["K", "K", "I", "I", "I", "I", "I", "L", "M", "M", "J", "J", "J"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
