import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/245",
  size: 15,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "B", "B"],
    ["C", "A", "A", "C", "A", "A", "A", "A", "A", "B", "B", "B", "B", "B", "B"],
    ["C", "C", "A", "C", "A", "A", "A", "A", "D", "D", "D", "D", "D", "D", "D"],
    ["C", "C", "C", "C", "A", "A", "A", "D", "D", "D", "D", "D", "E", "D", "D"],
    ["C", "C", "C", "C", "C", "C", "A", "A", "A", "D", "D", "E", "E", "D", "D"],
    ["C", "F", "G", "G", "C", "A", "A", "A", "A", "D", "E", "E", "E", "E", "D"],
    ["F", "F", "F", "F", "C", "A", "A", "A", "F", "D", "E", "E", "E", "E", "D"],
    ["H", "F", "F", "F", "F", "F", "F", "F", "F", "F", "E", "E", "E", "I", "I"],
    ["H", "F", "F", "F", "F", "F", "F", "F", "F", "F", "E", "E", "I", "I", "I"],
    ["H", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "E", "J", "J", "I"],
    ["H", "F", "F", "F", "F", "F", "K", "K", "K", "K", "K", "L", "J", "J", "J"],
    ["H", "F", "H", "H", "F", "H", "K", "M", "K", "K", "K", "L", "J", "J", "J"],
    ["H", "H", "H", "H", "H", "H", "H", "M", "K", "K", "K", "K", "J", "J", "J"],
    ["H", "H", "H", "H", "H", "N", "N", "N", "K", "K", "K", "K", "K", "K", "J"],
    ["H", "H", "H", "H", "H", "O", "O", "O", "O", "K", "K", "K", "K", "K", "J"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
