import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/296",
  size: 14,
  colorRegions: [
    ["A", "A", "A", "A", "B", "B", "A", "A", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "C", "C", "C", "C", "C", "C"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "C", "D", "D", "D", "D", "D"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "C", "D", "D", "E", "E", "E"],
    ["F", "A", "A", "A", "A", "A", "A", "A", "C", "G", "G", "E", "H", "E"],
    ["F", "F", "A", "A", "A", "A", "A", "A", "C", "G", "E", "E", "H", "E"],
    ["F", "F", "F", "A", "A", "A", "I", "A", "C", "G", "G", "E", "E", "E"],
    ["F", "F", "F", "F", "F", "F", "I", "I", "I", "I", "I", "I", "E", "E"],
    ["F", "F", "F", "F", "F", "J", "K", "I", "I", "I", "I", "I", "I", "E"],
    ["L", "L", "F", "F", "J", "J", "K", "I", "I", "I", "I", "I", "I", "I"],
    ["L", "L", "F", "F", "J", "J", "K", "I", "I", "F", "I", "I", "I", "M"],
    ["L", "L", "F", "F", "F", "F", "F", "F", "F", "F", "I", "I", "M", "M"],
    ["N", "N", "N", "F", "F", "F", "F", "F", "F", "I", "I", "M", "M", "M"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
  },
  solutionsCount: -1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
