import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/270",
  size: 15,
  colorRegions: [
    ["A", "B", "B", "B", "B", "B", "B", "B", "B", "B", "C", "C", "C", "D", "D"],
    ["B", "B", "F", "F", "B", "F", "F", "B", "B", "B", "B", "C", "D", "D", "D"],
    ["B", "F", "F", "F", "F", "F", "F", "F", "B", "O", "D", "D", "D", "D", "D"],
    ["B", "F", "F", "F", "F", "F", "F", "F", "O", "O", "D", "G", "G", "J", "D"],
    ["B", "B", "F", "F", "F", "F", "F", "O", "O", "O", "O", "G", "J", "J", "D"],
    ["B", "B", "B", "F", "F", "F", "O", "O", "O", "O", "O", "G", "G", "J", "D"],
    ["I", "B", "B", "B", "F", "O", "O", "O", "O", "O", "O", "G", "J", "J", "J"],
    ["I", "I", "B", "O", "O", "O", "O", "O", "O", "O", "O", "G", "O", "O", "O"],
    ["I", "B", "B", "O", "O", "O", "H", "O", "O", "O", "O", "O", "O", "O", "O"],
    ["I", "B", "B", "O", "O", "H", "H", "H", "O", "O", "K", "K", "K", "O", "O"],
    ["B", "B", "O", "O", "H", "H", "L", "L", "L", "K", "K", "K", "K", "K", "O"],
    ["B", "B", "O", "H", "H", "M", "L", "L", "K", "K", "K", "K", "K", "K", "K"],
    ["B", "B", "H", "H", "M", "M", "L", "N", "K", "K", "K", "K", "K", "K", "K"],
    ["B", "H", "H", "M", "M", "M", "M", "N", "N", "K", "K", "K", "K", "K", "E"],
    ["M", "M", "M", "M", "M", "M", "M", "N", "N", "N", "K", "K", "K", "E", "E"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
