import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/237",
  size: 13,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "B", "B", "B", "C", "C", "C", "C"],
    ["A", "D", "D", "E", "E", "B", "B", "B", "B", "C", "C", "C", "C"],
    ["F", "F", "E", "E", "E", "E", "B", "B", "B", "C", "C", "C", "C"],
    ["F", "F", "E", "E", "E", "B", "B", "B", "B", "B", "C", "C", "C"],
    ["F", "F", "E", "E", "E", "B", "B", "B", "B", "B", "C", "C", "C"],
    ["F", "G", "E", "E", "E", "B", "E", "B", "B", "B", "C", "C", "C"],
    ["F", "G", "G", "G", "E", "E", "E", "B", "H", "C", "C", "C", "C"],
    ["G", "G", "G", "G", "G", "G", "E", "H", "H", "C", "C", "H", "C"],
    ["G", "G", "G", "G", "I", "G", "G", "H", "H", "H", "H", "H", "H"],
    ["G", "G", "G", "G", "I", "I", "I", "H", "H", "H", "H", "J", "J"],
    ["G", "K", "G", "G", "I", "L", "L", "H", "H", "J", "J", "J", "M"],
    ["G", "K", "K", "G", "I", "L", "L", "L", "J", "J", "J", "M", "M"],
    ["K", "K", "K", "K", "I", "I", "I", "I", "I", "J", "J", "J", "M"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
