import {
  altoMain,
  anakiwa,
  bittersweet,
  canCan,
  celadon,
  chardonnay,
  halfBaked,
  lightOrchid,
  lightWisteria,
  malibu,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/195",
  size: 13,
  colorRegions: [
    ["L", "B", "B", "B", "C", "D", "D", "D", "D", "D", "E", "E", "E"],
    ["B", "B", "B", "C", "C", "D", "D", "D", "D", "E", "E", "E", "E"],
    ["B", "B", "C", "C", "C", "D", "D", "D", "D", "E", "E", "E", "E"],
    ["C", "C", "C", "C", "D", "D", "E", "D", "E", "E", "E", "E", "E"],
    ["C", "C", "F", "F", "F", "D", "E", "E", "E", "E", "E", "E", "E"],
    ["C", "C", "C", "F", "D", "D", "E", "E", "E", "E", "E", "E", "E"],
    ["C", "C", "F", "F", "E", "E", "E", "H", "H", "G", "G", "G", "G"],
    ["F", "F", "F", "F", "E", "E", "E", "G", "G", "G", "G", "G", "G"],
    ["F", "F", "F", "F", "F", "F", "E", "G", "G", "I", "I", "G", "I"],
    ["F", "F", "F", "J", "J", "F", "F", "G", "K", "K", "I", "I", "I"],
    ["M", "M", "F", "J", "J", "F", "K", "K", "K", "K", "K", "I", "I"],
    ["M", "M", "M", "M", "J", "F", "F", "K", "K", "K", "A", "A", "A"],
    ["M", "M", "M", "M", "J", "J", "F", "F", "F", "K", "A", "A", "A"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: lightOrchid,
    G: saharaSand,
    H: bittersweet,
    I: nomad,
    J: halfBaked,
    K: turquoiseBlue,
    L: canCan,
    M: malibu,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
