import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/220",
  size: 13,
  colorRegions: [
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A"],
    ["A", "A", "A", "A", "A", "A", "A", "B", "B", "A", "A", "A", "A"],
    ["C", "A", "A", "A", "A", "A", "B", "B", "B", "A", "A", "A", "D"],
    ["C", "C", "C", "A", "A", "B", "B", "B", "B", "A", "A", "A", "D"],
    ["C", "E", "C", "A", "A", "B", "B", "B", "B", "A", "A", "A", "D"],
    ["E", "E", "E", "A", "E", "F", "F", "F", "B", "B", "B", "B", "D"],
    ["E", "E", "E", "E", "E", "F", "F", "F", "F", "F", "B", "G", "G"],
    ["E", "E", "E", "E", "E", "E", "H", "H", "F", "F", "F", "G", "G"],
    ["E", "E", "I", "I", "I", "E", "H", "H", "F", "F", "F", "F", "G"],
    ["E", "E", "E", "I", "J", "E", "E", "E", "E", "F", "F", "F", "G"],
    ["K", "K", "K", "K", "J", "J", "J", "E", "L", "L", "L", "L", "L"],
    ["K", "K", "K", "K", "K", "K", "J", "E", "J", "M", "M", "L", "L"],
    ["K", "K", "K", "K", "K", "K", "J", "J", "J", "J", "J", "J", "J"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
  },
  solutionsCount: 1,
  createdBy: "mattsemar",
  creatorLink: "https://github.com/mattsemar",
};

export default level;
